component: scf
name: event

inputs:
  src:
    src: ./src
    exclude:
      - .env
  # type: event
  # region: ap-guangzhou
  # runtime: Nodejs12.16
  name: event-function
  handler: index.main_handler
  events:
    - apigw:
        parameters:
          protocols:
            - http
            - https
          environment: release
          endpoints:
            - path: /
              method: ANY
