component: scf
name: imageeventdemo

inputs:
  name: event-function-image
  region: ap-chengdu
  image:
    imageType: enterprise
    registryId: ${env:registry_id} # 请修改为指定容器镜像服务实例 ID
    imageUrl: ${env:image_url} # 请修改为指定镜像版本 URL
  events:
    - apigw:
        parameters:
          protocols:
            - http
            - https
          environment: release
          endpoints:
            - path: /
              method: ANY
