component: scf
name: imageeventdemo

inputs:
  name: event-function-image
  region: ap-chengdu
  image:
    imageType: enterprise
    registryId: ${env:registry_id}
    imageUri: ${env:image_uri}
  events:
    - apigw:
        parameters:
          protocols:
            - http
            - https
          environment: release
          endpoints:
            - path: /
              method: ANY
