component: scf
name: imagedemo

inputs:
  name: web-function-image
  region: ap-chengdu
  # 指定 SCF 类型为 Web 类型
  type: web
  image:
    imageType: personal
    imageUrl: ${env:image_url} # 请修改为指定镜像版本 URL
  events:
    - apigw:
        parameters:
          protocols:
            - http
            - https
          environment: release
          endpoints:
            - path: /
              method: ANY
              function:
                type: web
