component: scf
name: http

inputs:
  src:
    src: ./src
    exclude:
      - .env
  # 指定 SCF 类型为 Web 类型
  type: web
  name: web-function
  region: ap-chengdu
  runtime: Nodejs12.16
  # 无 scf_bootstrap 文件时指定入口文件名
  entryFile: 'app.js'
  events:
    - apigw:
        parameters:
          protocols:
            - http
            - https
          environment: release
          endpoints:
            - path: /
              method: ANY
